backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - name: article
    label: Article
    folder: articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }